### ISSUE TITLE
Displaying updted wait time

### ISSUE THREAD

**Issue by ngolini22** [jfeiber/buzzer#151] opened 2017-02-09 19:55 UTC
During dogfooding I overheard someone saying that you guys did not want to keep the wait time updated on the buzzers. When I took the buzzer out of the room, I wanted to know what my current wait time was because I couldn't remember how long it had been since my buzzer was set up for my party. I think just having the timer update itself every 5 minutes could be effective. It seems like one of your main selling points on the buzzer is that people can take it down the street or go do something while waiting for a long expected wait time. If the time started going down on the buzzer with current expected wait times, people would probably be more inclined to getting ready to head back to the restaurant with 5-10 minutes left, rather than waiting to be buzzed while half a mile down the road. If you really don't want to update the wait time on the buzzer screen, I think one good work-around could be displaying the time at which the buzzer was linked to a party.

**Comment by jfeiber** [comment] 2017-02-12 20:47
Closing. Duplicate of https://github.com/jfeiber/buzzer/issues/142.

**Closed as completed by jfeiber** 2017-02-12 20:47 UTC
